[package]
name = "octets"
version = "0.1.0"
edition = "2018"
authors = ["Martin Hoffmann <martin@nlnetlabs.nl>"]
description = "Abstractions for types representing octet sequences."
documentation = "https://docs.rs/octets"
homepage = "https://github.com/NLnetLabs/octets/"
readme = "README.md"
keywords = ["octets", "bytes", "generics"]
license = "BSD-3-Clause"

[dependencies]
bytes    = { version = "1.0", optional = true }
smallvec = { version = "1.0", optional = true }

[features]
default = ["std"]
std     = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

